workflows:
  android-manual-gradle:
    name: Android Manual Gradle Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    scripts:
      - name: Install system Gradle
        script: |
          sudo apt-get update
          sudo apt-get install -y gradle
      - name: Build Debug APK
        script: |
          cd android
          gradle assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
