
workflows:
  native-react-native:
    name: Build APK (Pure React Native)
    max_build_duration: 60
    environment:
      node: 18
    scripts:
      - npm install
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
